#!/usr/bin/env bash
# Builds a clickable "type-by-voice.app" into ~/Applications (Launchpad + Dock),
# the macOS counterpart of install-desktop.sh. Run after setting up the venv
# (see README → macOS).
#
# The .app just launches the repo's ./voice-term, but wrapping it as a proper
# app bundle means macOS attributes the Accessibility / Input Monitoring / mic
# permissions to "type-by-voice" (by name, and they persist) instead of to
# whatever terminal you happened to run it from.
set -euo pipefail

HERE="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
VENV="$HERE/.venv"

if [[ ! -x "$VENV/bin/python" ]]; then
    echo "venv not found at $VENV." >&2
    echo "Set it up first (see README → macOS):" >&2
    echo "  brew install portaudio" >&2
    echo "  python3 -m venv .venv && .venv/bin/pip install -r requirements-macos.txt" >&2
    exit 1
fi

APP="$HOME/Applications/type-by-voice.app"
MACOS="$APP/Contents/MacOS"
RES="$APP/Contents/Resources"

echo "Building $APP ..."
rm -rf "$APP"
mkdir -p "$MACOS" "$RES"

# --- launcher: the app's executable execs the venv launcher ---------------- #
cat > "$MACOS/type-by-voice" <<EOF
#!/bin/bash
# Auto-generated by install-app-macos.sh. Launches voice-term from its repo.
exec "$HERE/voice-term"
EOF
chmod +x "$MACOS/type-by-voice"

# --- Info.plist ------------------------------------------------------------ #
cat > "$APP/Contents/Info.plist" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>            <string>type-by-voice</string>
    <key>CFBundleDisplayName</key>     <string>type-by-voice</string>
    <key>CFBundleIdentifier</key>      <string>com.github.kotaro-nakata.type-by-voice</string>
    <key>CFBundleExecutable</key>      <string>type-by-voice</string>
    <key>CFBundleIconFile</key>        <string>AppIcon</string>
    <key>CFBundlePackageType</key>     <string>APPL</string>
    <key>CFBundleShortVersionString</key> <string>0.1.0</string>
    <key>CFBundleVersion</key>         <string>0.1.0</string>
    <key>LSMinimumSystemVersion</key>  <string>11.0</string>
    <key>NSMicrophoneUsageDescription</key>
    <string>type-by-voice records the microphone while you hold the hotkey to transcribe your speech locally.</string>
    <key>NSHumanReadableCopyright</key> <string>MIT</string>
</dict>
</plist>
EOF

# --- icon (best effort): draw a mic squircle, convert to .icns ------------- #
if "$VENV/bin/python" - "$RES/icon-1024.png" <<'PYEOF'
import sys, zlib, struct
try:
    import numpy as np
except Exception:
    sys.exit(2)

out = sys.argv[1]
N = 1024
yy, xx = np.mgrid[0:N, 0:N].astype(float)
c = N / 2.0
img = np.zeros((N, N, 4), dtype=np.uint8)

# Big-Sur-style squircle (superellipse), ~84% of the canvas, transparent outside.
a = N * 0.42
sq = (np.abs((xx - c) / a) ** 5 + np.abs((yy - c) / a) ** 5) <= 1.0

# Vertical indigo->violet gradient inside the squircle.
t = np.clip((yy - (c - a)) / (2 * a), 0, 1)
top = np.array([79, 70, 229]); bot = np.array([147, 51, 234])
grad = (top[None, None] * (1 - t)[..., None] + bot[None, None] * t[..., None]).astype(np.uint8)
img[sq, 0:3] = grad[sq]; img[sq, 3] = 255

def rrect(px, py, hw, hh, r):
    ax = np.abs(xx - px); ay = np.abs(yy - py)
    within = (ax <= hw) & (ay <= hh)
    crx = ax - (hw - r); cry = ay - (hh - r)
    corner = (crx > 0) & (cry > 0)
    return within & (~corner | ((crx ** 2 + cry ** 2) <= r ** 2))

# White microphone: capsule body + U cradle + stem + base.
body = rrect(c, 430, 95, 150, 95)
d = np.sqrt((xx - c) ** 2 + (yy - 430) ** 2)
cradle = (d <= 175) & (d >= 140) & (yy >= 440)
stem = rrect(c, 655, 12, 60, 12)
base = rrect(c, 725, 95, 16, 16)
mic = body | cradle | stem | base
img[mic, 0:3] = [255, 255, 255]; img[mic, 3] = 255

def png(path, a8):
    h, w = a8.shape[:2]
    raw = b"".join(b"\x00" + a8[y].tobytes() for y in range(h))
    def ch(t, d):
        return struct.pack(">I", len(d)) + t + d + struct.pack(">I", zlib.crc32(t + d) & 0xffffffff)
    with open(path, "wb") as f:
        f.write(b"\x89PNG\r\n\x1a\n")
        f.write(ch(b"IHDR", struct.pack(">IIBBBBB", w, h, 8, 6, 0, 0, 0)))
        f.write(ch(b"IDAT", zlib.compress(raw, 9)))
        f.write(ch(b"IEND", b""))

png(out, img)
PYEOF
then
    # Build the .icns from a proper multi-size iconset (iconutil is reliable;
    # sips' direct png->icns often fails with "Error 13").
    ISET="$(mktemp -d)/AppIcon.iconset"
    mkdir -p "$ISET"
    for s in 16 32 128 256 512; do
        s2=$((s * 2))
        sips -z "$s"  "$s"  "$RES/icon-1024.png" --out "$ISET/icon_${s}x${s}.png"    >/dev/null 2>&1
        sips -z "$s2" "$s2" "$RES/icon-1024.png" --out "$ISET/icon_${s}x${s}@2x.png" >/dev/null 2>&1
    done
    if iconutil -c icns "$ISET" -o "$RES/AppIcon.icns" >/dev/null 2>&1; then
        echo "Icon generated."
    else
        echo "[warn] iconutil could not build the icns; using the default icon."
    fi
    rm -rf "$ISET" "$RES/icon-1024.png"
else
    echo "[warn] Could not generate the icon (numpy missing?); using the default icon."
fi

# --- ad-hoc sign so macOS gives the app a stable identity ------------------ #
# This lets the Accessibility / Input Monitoring permission you grant persist
# across relaunches (TCC keys apps by code signature).
codesign --force --deep -s - "$APP" >/dev/null 2>&1 \
    && echo "Ad-hoc signed." || echo "[warn] codesign unavailable; app is unsigned."

# Nudge Launchpad/Finder to notice the new app.
touch "$APP"
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister \
    -f "$APP" >/dev/null 2>&1 || true

echo
echo "Installed: $APP"
echo "Find 'type-by-voice' in Launchpad (or ~/Applications) and click to start."
echo "On first use, macOS will ask for Microphone, Accessibility and Input"
echo "Monitoring permission — grant all three. Quit from the Dock icon (right-click → Quit)."
